[project]
name = "todo-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Slokem"}
]
requires-python = ">=3.10"
dependencies = [
    "typer"
]
